Investo/Controllers/InvestmentController.cs
using System;
using Investo.Interface.Services;
using Microsoft.AspNetCore.Mvc;

namespace Investo.Controllers
{
    public class InvestmentController : Controller
    {

        private readonly IInvestmentService _investmentService;


        public InvestmentController(IInvestmentService investmentService)
        {
            _investmentService = investmentService;
        }


        //[HttpGet]
        //public IActionResult Index()
        //{
        //    return View(_investmentService.GetAll());
        //}


    }
}

Investo/Views/Shared/_Layout.cshtml
@using  Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Investo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-litera.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <i class="fab fa-studiovinari"></i>Investo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Investor" asp-action="Index">Investors</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Index">Managers</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Investment" asp-action="Index">Investments</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admins</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>


                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item border-left">
                            <a class="nav-link text-dark border-left" asp-area="" asp-controller="Investor" asp-action="Login"><i class="fas fa-sign-out-alt"></i> &nbsp; SignUp</a>
                        </li>


                        <li class="nav-item border-left">
                            <a class="nav-link text-dark border-left" asp-area="" asp-controller="Investor" asp-action="Login"> <i class="fas fa-sign-in-alt"></i> &nbsp; Login</a>
                        </li>





                        <li class="nav-item ml-auto">
                            @if (signInManager.IsSignedIn(User))
                            {
                                @*<li class="nav-item">*@
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>

                                    @*<a class="nav-link text-dark border-left" asp-controller="Account" asp-action="Register"> <i class="fas fa-registered"></i> &nbsp; Register</a>*@
                                </form>
                                @*</li>*@
                            }
                            else
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark border-left" asp-controller="Account" asp-action="Register"> <i class="fas fa-registered"></i> &nbsp; Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark border-left" asp-controller="Account" asp-action="Login"> <i class="fas fa-sign-in-alt"></i> &nbsp; Login</a>
                            </li>
                        }


                            @*<a class="nav-link text-dark border-left" asp-area="" asp-controller="Account" asp-action="Register"> <i class="fas fa-registered"></i> &nbsp; Register</a>
                                </li>*@


                        </ul>



                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - <i class="fab fa-studiovinari"></i> &nbsp; Investo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>